"""
PRisk LangGraph State
--------------------------
This is the single shared data object that flows through every node in the
LangGraph workflow. Think of it as a "baton" passed from agent to agent.

Each agent reads what it needs and writes its output back into this dict.
LangGraph takes care of passing the updated state to the next node.
"""

import operator
from typing import Annotated, TypedDict, List, Dict, Any


class PRiskState(TypedDict):
    # ── INPUT ──────────────────────────────────────────────────────────────
    # The raw GitHub PR URL the user submitted
    pr_url: str

    # ── REPOSITORY CONTEXT (populated by Context Builder) ──────────────────
    # "owner/repo" extracted from the URL
    repo_name: str

    # The full text diff of the PR (e.g. "--- a/foo.java\n+++ b/foo.java\n...")
    diff: str

    # List of file paths that were changed in this PR
    changed_files: List[str]

    # A plain-English summary of the repository structure, generated by LLM.
    # Example: "Spring Boot e-commerce app with User, Order, Payment modules."
    repo_summary: str

    # Evidence mined from git history: per-changed-file churn, fix/revert
    # counts, hotspot flags. Populated by mine_history_risk in context_builder.
    history_risk: Dict[str, Any]

    # Measured import-graph evidence: which files actually import the changed
    # code, with line-number citations. Populated by build_dependency_evidence.
    dependency_evidence: Dict[str, Any]
    # PR metadata carried through the analysis response.
    pr_title: str
    pr_description: str
    author: str
    name: str
    # ── AGENT OUTPUTS ──────────────────────────────────────────────────────

    # Agent 1: What changed and why?
    change_analysis: Dict[str, Any]
    # Example shape:
    # {
    #   "summary": "User API now returns DTO objects",
    #   "change_type": "API Contract Change",
    #   "affected_module": "User Management",
    #   "complexity": "Medium",
    #   "estimated_lines_changed": 42
    # }

    # Agent 2: What might break?
    blast_radius: Dict[str, Any]
    # Example shape:
    # {
    #   "affected_modules": ["UserController", "OrderService"],
    #   "impact_level": "High",
    #   "reasoning": "UserService is used by 3 downstream services...",
    #   "dependency_chain": ["UserService -> OrderService -> PaymentService"]
    # }

    # Agent 3: Code quality issues
    engineering_review: Dict[str, Any]
    # Example shape:
    # {
    #   "security": ["Input validation missing on userId param"],
    #   "performance": ["Potential N+1 query in getOrders()"],
    #   "maintainability": ["Method doEverything() is 200 lines - split it"],
    #   "code_quality": ["Duplicate logic in UserService and AdminService"],
    #   "severity": "Medium"
    # }

    # Agent 4: What tests are needed?
    testing_strategy: Dict[str, Any]
    # Example shape:
    # {
    #   "missing_tests": ["DTO mapping test", "Null input test"],
    #   "edge_cases": ["What if userId is 0?", "Concurrent requests?"],
    #   "regression_risks": ["Login flow may break if UserDTO fields change"],
    #   "recommended_test_types": ["Unit", "Integration", "Contract"]
    # }

    # Agent 5: Final verdict
    confidence_report: Dict[str, Any]
    # Example shape:
    # {
    #   "score": 68,
    #   "recommendation": "Needs Validation",
    #   "breakdown": {
    #     "blast_radius_score": 30,
    #     "engineering_score": 25,
    #     "testing_score": 13,
    #     "complexity_score": 0
    #   },
    #   "summary": "High blast radius and missing tests reduce confidence."
    # }

    # ── ERROR TRACKING ────────────────────────────────────────────────────
    # If any agent fails, it writes the error here so the graph can continue
    errors: Annotated[List[str], operator.add]
