import { AnalysisResult, Finding } from './analysis.service';

/**
 * Renders the full analysis as GitHub-flavoured Markdown, ready to paste
 * into the PR conversation — so the risk report lives where the merge
 * decision actually happens.
 */
export function buildMarkdownReport(r: AnalysisResult): string {
  const cr = r.confidence_report;
  const ca = r.change_analysis;
  const br = r.blast_radius;
  const er = r.engineering_review;
  const ts = r.testing_strategy;

  const hr = r.history_risk;

  const emoji = cr.recommendation_color === 'green' ? '🟢' : cr.recommendation_color === 'red' ? '🔴' : '🟡';
  const list = (items: string[], empty = '_None identified._') =>
    items?.length ? items.map((i) => `- ${i}`).join('\n') : empty;
  const findingList = (items: Finding[]) =>
    items?.length
      ? items.map((f) => `- **[${f.severity}]** ${f.text} _(${f.effort})_`).join('\n')
      : '';

  const de = r.dependency_evidence;
  const measured =
    de?.available && de.edges.length
      ? `\n### Measured dependents _(parsed from import statements — not AI inference)_\n\n${de.edges
          .map((e) => `- \`${e.from_file}:${e.line}\` → \`${e.to_file}\`\n  \`${e.code}\``)
          .join('\n')}\n`
      : de?.available
        ? `\n### Measured dependents\n\n_Import scan found no files depending on the changed code (${de.files_scanned} files scanned)._\n`
        : '';

  const evidence =
    hr?.available && hr.files.length
      ? `\n### Historical risk evidence _(last ${hr.window_commits} commits)_\n\n${hr.files
          .map(
            (f) =>
              `- \`${f.path}\` — ${f.fix_commits} fix/revert commit${f.fix_commits === 1 ? '' : 's'}, ${f.commits} total change${f.commits === 1 ? '' : 's'}${hr.hotspots.includes(f.path) ? ' — **⚠ hotspot**' : ''}`,
          )
          .join('\n')}\n`
      : '';

  return `## ${emoji} PRisk Score: ${cr.score}/100 — ${cr.recommendation}

**PR:** [${r.name || r.pr_title}](${r.pr_url}) · **Repo:** \`${r.repo_name}\` · **Author:** @${r.author}
${r.analysis_quality && r.analysis_quality.mode !== 'full' ? `\n> ⚠️ **${r.analysis_quality.mode === 'degraded' ? 'Heuristic analysis' : 'Partial AI analysis'}:** ${r.analysis_quality.note}\n` : ''}
> ${cr.executive_summary}

### Score breakdown

| Dimension | Score | Signal |
| --- | --- | --- |
| Blast Radius | ${cr.breakdown.blast_radius_score}/${cr.breakdown.blast_radius_max} | ${cr.input_levels.blast_radius_level} |
| Engineering | ${cr.breakdown.engineering_score}/${cr.breakdown.engineering_max} | ${cr.input_levels.engineering_severity} |
| Testing | ${cr.breakdown.testing_score}/${cr.breakdown.testing_max} | ${cr.input_levels.testing_assessment} |
| Complexity | ${cr.breakdown.complexity_score}/${cr.breakdown.complexity_max} | ${cr.input_levels.complexity} |

<details>
<summary>Why these scores (signal-level drivers)</summary>

${(['blast_radius', 'engineering', 'testing', 'complexity'] as const)
  .map((key) => {
    const drivers = cr.score_drivers?.[key] ?? [];
    if (!drivers.length) return '';
    const title = key.replace('_', ' ').replace(/\b\w/g, (c) => c.toUpperCase());
    return `**${title}**\n${drivers.map((d) => `- ${d.label}: ${d.points > 0 ? '+' : ''}${d.points}`).join('\n')}\n`;
  })
  .join('\n')}
</details>

### What changed

${ca.summary}

- **Type:** ${ca.change_type} · **Complexity:** ${ca.complexity} · **~Lines:** ${ca.estimated_lines_changed}
- **Module:** ${ca.affected_module}

### Blast radius — ${br.impact_level}

${br.reasoning}

**Potentially impacted:** ${br.affected_modules.join(', ') || '—'}

${list(br.dependency_chain.map((c) => `\`${c}\``), '')}

**User flows at risk:** ${br.user_flows_at_risk.join(', ') || '—'}
${measured}${evidence}
### Engineering review — ${er.overall_severity} (${er.total_issues_found} issue${er.total_issues_found === 1 ? '' : 's'})

${er.security.length ? `**Security**\n${findingList(er.security)}\n` : ''}${er.code_quality.length ? `**Code quality**\n${findingList(er.code_quality)}\n` : ''}${er.maintainability.length ? `**Maintainability**\n${findingList(er.maintainability)}\n` : ''}${er.performance.length ? `**Performance**\n${findingList(er.performance)}\n` : ''}${!er.total_issues_found ? '_No material issues found._\n' : ''}
### Tests to add before merge — ${ts.test_coverage_assessment}

${list(ts.priority_tests.map((t, i) => `**P${i + 1}.** ${t.text} _(${t.effort})_`))}

<details>
<summary>All recommended tests (${ts.total_tests_recommended})</summary>

**Missing tests**
${list(ts.missing_tests)}

**Edge cases**
${list(ts.edge_cases)}

**Regression risks**
${list(ts.regression_risks)}

</details>

---
_Generated by [PRisk](https://p-risk.vercel.app) — AI pull-request risk intelligence._`;
}
