import { AnalysisResult } from './analysis.service';

/**
 * Renders the full analysis as GitHub-flavoured Markdown, ready to paste
 * into the PR conversation — so the risk report lives where the merge
 * decision actually happens.
 */
export function buildMarkdownReport(r: AnalysisResult): string {
  const cr = r.confidence_report;
  const ca = r.change_analysis;
  const br = r.blast_radius;
  const er = r.engineering_review;
  const ts = r.testing_strategy;

  const emoji = cr.recommendation_color === 'green' ? '🟢' : cr.recommendation_color === 'red' ? '🔴' : '🟡';
  const list = (items: string[], empty = '_None identified._') =>
    items?.length ? items.map((i) => `- ${i}`).join('\n') : empty;

  return `## ${emoji} PRisk Analysis — ${cr.score}/100 · ${cr.recommendation}

**PR:** [${r.name || r.pr_title}](${r.pr_url}) · **Repo:** \`${r.repo_name}\` · **Author:** @${r.author}

> ${cr.executive_summary}

### Score breakdown

| Dimension | Score | Signal |
| --- | --- | --- |
| Blast Radius | ${cr.breakdown.blast_radius_score}/${cr.breakdown.blast_radius_max} | ${cr.input_levels.blast_radius_level} |
| Engineering | ${cr.breakdown.engineering_score}/${cr.breakdown.engineering_max} | ${cr.input_levels.engineering_severity} |
| Testing | ${cr.breakdown.testing_score}/${cr.breakdown.testing_max} | ${cr.input_levels.testing_assessment} |
| Complexity | ${cr.breakdown.complexity_score}/${cr.breakdown.complexity_max} | ${cr.input_levels.complexity} |

### What changed

${ca.summary}

- **Type:** ${ca.change_type} · **Complexity:** ${ca.complexity} · **~Lines:** ${ca.estimated_lines_changed}
- **Module:** ${ca.affected_module}

### Blast radius — ${br.impact_level}

${br.reasoning}

**Potentially impacted:** ${br.affected_modules.join(', ') || '—'}

${list(br.dependency_chain.map((c) => `\`${c}\``), '')}

**User flows at risk:** ${br.user_flows_at_risk.join(', ') || '—'}

### Engineering review — ${er.overall_severity} (${er.total_issues_found} issue${er.total_issues_found === 1 ? '' : 's'})

${er.security.length ? `**Security**\n${list(er.security)}\n` : ''}${er.code_quality.length ? `**Code quality**\n${list(er.code_quality)}\n` : ''}${er.maintainability.length ? `**Maintainability**\n${list(er.maintainability)}\n` : ''}${er.performance.length ? `**Performance**\n${list(er.performance)}\n` : ''}${!er.total_issues_found ? '_No material issues found._\n' : ''}
### Tests to add before merge — ${ts.test_coverage_assessment}

${list(ts.priority_tests.map((t, i) => `**P${i + 1}.** ${t}`))}

<details>
<summary>All recommended tests (${ts.total_tests_recommended})</summary>

**Missing tests**
${list(ts.missing_tests)}

**Edge cases**
${list(ts.edge_cases)}

**Regression risks**
${list(ts.regression_risks)}

</details>

---
_Generated by [PRisk](https://p-risk.vercel.app) — AI pull-request risk intelligence._`;
}
